version: '3.9'

services:
#  user_quest_app:
#    build: ./
#    command: ./wait-for-postgres.sh db ./concert-pre-poster
#    ports:
#      - 8000:8000
#    depends_on:
#      - db
#      - redis
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: nav461
#      POSTGRES_DB: postgres
#    hostname: concert-pre-poster
#    container_name: concert-pre-poster

  db_preposters:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nav461
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./concert-preposter-service/.postgres-data:/var/lib/postgresql/data

  db_articles:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nav461
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./article-service/.postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.redis-data:/data
    container_name: redis
